import { Inter } from "next/font/google";
import "./globals.css";
import { Heart } from "lucide-react";
import Header from "@/components/Header";
import { getUser } from "@/lib/getUser"; 

import {ClerkProvider} from "@clerk/nextjs"
import { neobrutalism } from "@clerk/themes";

const inter = Inter({subsets: ["latin"]});
export const metadata = {
  title: "Serve- AI Recipes Plateform",
  description: "Generated by create next app",
};
//server

// Login (Clerk)   ↓
// checkUserServer()
// Find user by clerkId in Strapi
// If not exists → create with default "free"
// If exists → sync plan if changed
// Return Strapi user

export default async function RootLayout({ children }) {
  const user = await getUser();
  // console.log("LAYOUT USER:", user);

  return (
    <ClerkProvider appearance={{baseTheme:neobrutalism}}>
    
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className}`}
      > 
      <Header user={user} />
      <main className="min-h-screen">
        {children}
      </main>
      <footer className="py-8 px-4 border-4" >
        <div className="max-w-6xl mx-auto flex justify-center items-center">
          <p className="text-stone-500 text-sm">
            Made with 
            <Heart className="mr-2 h-5 w-5 text-red-500 fill-red-500" /> by Sumit Khera
          </p>
        </div>
      </footer>
      </body>
    </html>
    </ClerkProvider>
  );
}